In [453]:
import pandas as pd
data = pd.read_csv("./employes.csv")
data.head()
data.tail()
data.info()
data.describe()
data.columns
data.dtypes
data.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   num_emp        14 non-null     int64
 1   nom_emp        14 non-null     str
 2   poste          14 non-null     str
 3   superieur      13 non-null     float64
 4   date_embauche  14 non-null     str
 5   salaire        14 non-null     int64
 6   commission     4 non-null      float64
 7   num_dep        14 non-null     int64
dtypes: float64(2), int64(3), str(3)
memory usage: 1.0 KB

num_emp           0
nom_emp           0
poste             0
superieur         1
date_embauche     0
salaire           0
commission       10
num_dep           0
dtype: int64

# PART 2

In [454]:
noms = data["nom_emp"]

In [455]:
noms_salaires = data[["nom_emp", "salaire"]]

In [456]:
# show lines from 1 to 4 keep all columns
print(noms_salaires.iloc[1:5])

    nom_emp  salaire
1    Parent     1600
2     Henry     1250
3  Dumoulin     2975
4    Ferron     1250

In [457]:
print(noms_salaires.loc[1:4])

    nom_emp  salaire
1    Parent     1600
2     Henry     1250
3  Dumoulin     2975
4    Ferron     1250

In [458]:
data.loc[2]

num_emp                7521
nom_emp               Henry
poste            Commercial
superieur            7698.0
date_embauche    1981-02-22
salaire                1250
commission            500.0
num_dep                  30
Name: 2, dtype: object

In [459]:
data.loc[1, 'poste']

'Commercial'

In [460]:
data.loc[0]

num_emp                7369
nom_emp           Coquillet
poste            Technicien
superieur            7902.0
date_embauche    1980-12-17
salaire                 800
commission              NaN
num_dep                  20
Name: 0, dtype: object

In [461]:
data.iloc[0]

num_emp                7369
nom_emp           Coquillet
poste            Technicien
superieur            7902.0
date_embauche    1980-12-17
salaire                 800
commission              NaN
num_dep                  20
Name: 0, dtype: object

In [462]:
data[data['salaire'] > 2000]

,num_emp,nom_emp,poste,superieur,date_embauche,salaire,commission,num_dep
3,7566,Dumoulin,Directeur,7839.0,1981-04-02,2975,NaN,20
5,7698,Capon,Directeur,7839.0,1981-05-01,2850,NaN,30
6,7782,Martin,Directeur,7839.0,1981-06-09,2450,NaN,10
7,7788,Colin,Analyste,7566.0,1987-04-19,3000,NaN,20
8,7839,Patton,Président,NaN,1981-11-17,5000,NaN,10
12,7902,Henry,Analyste,7566.0,1981-12-03,3000,NaN,20

In [463]:
data[data['poste'] == 'Technicien']

,num_emp,nom_emp,poste,superieur,date_embauche,salaire,commission,num_dep
0,7369,Coquillet,Technicien,7902.0,1980-12-17,800,NaN,20
10,7876,Calamon,Technicien,7788.0,1987-05-23,1100,NaN,20
11,7900,James,Technicien,7698.0,1981-12-03,950,NaN,30
13,7934,Tozzi,Technicien,7782.0,1982-01-23,1300,NaN,10

In [464]:
data[data['poste'].isin(['Technicien', 'Commercial'])]

,num_emp,nom_emp,poste,superieur,date_embauche,salaire,commission,num_dep
0,7369,Coquillet,Technicien,7902.0,1980-12-17,800,NaN,20
1,7499,Parent,Commercial,7698.0,1981-02-20,1600,300.0,30
2,7521,Henry,Commercial,7698.0,1981-02-22,1250,500.0,30
4,7654,Ferron,Commercial,7698.0,1981-09-28,1250,1400.0,30
9,7844,Benami,Commercial,7698.0,1981-09-08,1500,0.0,30
10,7876,Calamon,Technicien,7788.0,1987-05-23,1100,NaN,20
11,7900,James,Technicien,7698.0,1981-12-03,950,NaN,30
13,7934,Tozzi,Technicien,7782.0,1982-01-23,1300,NaN,10

# PART 3

In [465]:
data['Bonus'] = data['salaire'] * 0.1
data.head()

,num_emp,nom_emp,poste,superieur,date_embauche,salaire,commission,num_dep,Bonus
0,7369,Coquillet,Technicien,7902.0,1980-12-17,800,NaN,20,80.0
1,7499,Parent,Commercial,7698.0,1981-02-20,1600,300.0,30,160.0
2,7521,Henry,Commercial,7698.0,1981-02-22,1250,500.0,30,125.0
3,7566,Dumoulin,Directeur,7839.0,1981-04-02,2975,NaN,20,297.5
4,7654,Ferron,Commercial,7698.0,1981-09-28,1250,1400.0,30,125.0

In [466]:
data.drop('Bonus' , axis=1, inplace=True)
data.head()

,num_emp,nom_emp,poste,superieur,date_embauche,salaire,commission,num_dep
0,7369,Coquillet,Technicien,7902.0,1980-12-17,800,NaN,20
1,7499,Parent,Commercial,7698.0,1981-02-20,1600,300.0,30
2,7521,Henry,Commercial,7698.0,1981-02-22,1250,500.0,30
3,7566,Dumoulin,Directeur,7839.0,1981-04-02,2975,NaN,20
4,7654,Ferron,Commercial,7698.0,1981-09-28,1250,1400.0,30

In [467]:
data.rename(columns={'nom_emp': 'nom'}, inplace=True)
data.columns

Index(['num_emp', 'nom', 'poste', 'superieur', 'date_embauche', 'salaire',
       'commission', 'num_dep'],
      dtype='str')

In [468]:
data.sort_values(by='salaire', inplace=True)
data.head()

,num_emp,nom,poste,superieur,date_embauche,salaire,commission,num_dep
0,7369,Coquillet,Technicien,7902.0,1980-12-17,800,NaN,20
11,7900,James,Technicien,7698.0,1981-12-03,950,NaN,30
10,7876,Calamon,Technicien,7788.0,1987-05-23,1100,NaN,20
2,7521,Henry,Commercial,7698.0,1981-02-22,1250,500.0,30
4,7654,Ferron,Commercial,7698.0,1981-09-28,1250,1400.0,30

In [469]:
data.sort_values(by='date_embauche', ascending=False, inplace=True)
data.head()

,num_emp,nom,poste,superieur,date_embauche,salaire,commission,num_dep
10,7876,Calamon,Technicien,7788.0,1987-05-23,1100,NaN,20
7,7788,Colin,Analyste,7566.0,1987-04-19,3000,NaN,20
13,7934,Tozzi,Technicien,7782.0,1982-01-23,1300,NaN,10
11,7900,James,Technicien,7698.0,1981-12-03,950,NaN,30
12,7902,Henry,Analyste,7566.0,1981-12-03,3000,NaN,20

In [470]:

data.loc[len(data)] = [1000, 'ALI', 'RH', 7839.0, '2023-01-01', 4000, None, 20]
data.drop(14, inplace=True)

# tester le code suivant

In [471]:

nouvelle_ligne = pd.DataFrame({
    'num_emp': 1000,
    'nom': 'ALI',
    'poste':'RH',
    'superieur':7839.0,
    'date_embauche':'2023-01-01',
    'salaire':4000,
    'commission':None,
    'num_dep':20,
}, index=[5])
data.head()

,num_emp,nom,poste,superieur,date_embauche,salaire,commission,num_dep
10,7876,Calamon,Technicien,7788.0,1987-05-23,1100,NaN,20
7,7788,Colin,Analyste,7566.0,1987-04-19,3000,NaN,20
13,7934,Tozzi,Technicien,7782.0,1982-01-23,1300,NaN,10
11,7900,James,Technicien,7698.0,1981-12-03,950,NaN,30
12,7902,Henry,Analyste,7566.0,1981-12-03,3000,NaN,20

In [472]:
data = pd.concat([data.iloc[:5], nouvelle_ligne, data.iloc[5:]], ignore_index=True)
print(data)

    num_emp        nom       poste  superieur date_embauche  salaire  \
0      7876    Calamon  Technicien     7788.0    1987-05-23     1100
1      7788      Colin    Analyste     7566.0    1987-04-19     3000
2      7934      Tozzi  Technicien     7782.0    1982-01-23     1300
3      7900      James  Technicien     7698.0    1981-12-03      950
4      7902      Henry    Analyste     7566.0    1981-12-03     3000
5      1000        ALI          RH     7839.0    2023-01-01     4000
6      7839     Patton   Président        NaN    1981-11-17     5000
7      7654     Ferron  Commercial     7698.0    1981-09-28     1250
8      7844     Benami  Commercial     7698.0    1981-09-08     1500
9      7782     Martin   Directeur     7839.0    1981-06-09     2450
10     7698      Capon   Directeur     7839.0    1981-05-01     2850
11     7566   Dumoulin   Directeur     7839.0    1981-04-02     2975
12     7521      Henry  Commercial     7698.0    1981-02-22     1250
13     7499     Parent  Commercial     7698.0    1981-02-20     1600
14     7369  Coquillet  Technicien     7902.0    1980-12-17      800

   commission  num_dep
0         NaN       20
1         NaN       20
2         NaN       10
3         NaN       30
4         NaN       20
5        None       20
6         NaN       10
7      1400.0       30
8         0.0       30
9         NaN       10
10        NaN       30
11        NaN       20
12      500.0       30
13      300.0       30
14        NaN       20

In [473]:
data.drop(5, inplace=True)
print(data)

    num_emp        nom       poste  superieur date_embauche  salaire  \
0      7876    Calamon  Technicien     7788.0    1987-05-23     1100
1      7788      Colin    Analyste     7566.0    1987-04-19     3000
2      7934      Tozzi  Technicien     7782.0    1982-01-23     1300
3      7900      James  Technicien     7698.0    1981-12-03      950
4      7902      Henry    Analyste     7566.0    1981-12-03     3000
6      7839     Patton   Président        NaN    1981-11-17     5000
7      7654     Ferron  Commercial     7698.0    1981-09-28     1250
8      7844     Benami  Commercial     7698.0    1981-09-08     1500
9      7782     Martin   Directeur     7839.0    1981-06-09     2450
10     7698      Capon   Directeur     7839.0    1981-05-01     2850
11     7566   Dumoulin   Directeur     7839.0    1981-04-02     2975
12     7521      Henry  Commercial     7698.0    1981-02-22     1250
13     7499     Parent  Commercial     7698.0    1981-02-20     1600
14     7369  Coquillet  Technicien     7902.0    1980-12-17      800

   commission  num_dep
0         NaN       20
1         NaN       20
2         NaN       10
3         NaN       30
4         NaN       20
6         NaN       10
7      1400.0       30
8         0.0       30
9         NaN       10
10        NaN       30
11        NaN       20
12      500.0       30
13      300.0       30
14        NaN       20

In [474]:
data.reset_index(drop=True, inplace=True)
data.head()

,num_emp,nom,poste,superieur,date_embauche,salaire,commission,num_dep
0,7876,Calamon,Technicien,7788.0,1987-05-23,1100,NaN,20
1,7788,Colin,Analyste,7566.0,1987-04-19,3000,NaN,20
2,7934,Tozzi,Technicien,7782.0,1982-01-23,1300,NaN,10
3,7900,James,Technicien,7698.0,1981-12-03,950,NaN,30
4,7902,Henry,Analyste,7566.0,1981-12-03,3000,NaN,20

In [475]:
data.set_index('nom', inplace=True)
data.head()

,num_emp,poste,superieur,date_embauche,salaire,commission,num_dep
nom,,,,,,,
Calamon,7876,Technicien,7788.0,1987-05-23,1100,NaN,20
Colin,7788,Analyste,7566.0,1987-04-19,3000,NaN,20
Tozzi,7934,Technicien,7782.0,1982-01-23,1300,NaN,10
James,7900,Technicien,7698.0,1981-12-03,950,NaN,30
Henry,7902,Analyste,7566.0,1981-12-03,3000,NaN,20

In [476]:
data.reset_index(inplace=True)
data.head()

,nom,num_emp,poste,superieur,date_embauche,salaire,commission,num_dep
0,Calamon,7876,Technicien,7788.0,1987-05-23,1100,NaN,20
1,Colin,7788,Analyste,7566.0,1987-04-19,3000,NaN,20
2,Tozzi,7934,Technicien,7782.0,1982-01-23,1300,NaN,10
3,James,7900,Technicien,7698.0,1981-12-03,950,NaN,30
4,Henry,7902,Analyste,7566.0,1981-12-03,3000,NaN,20

# Partie 4

In [477]:
moyenne_salaire = data['salaire'].mean()
print(f"la moyenne des salaires est : {moyenne_salaire:.2f}")

la moyenne des salaires est : 2073.21

In [478]:
somme_salaire = data['salaire'].sum()
print(f"la somme des salaires est : {somme_salaire:.2f}")

la somme des salaires est : 29025.00

In [479]:
salaire_max = data['salaire'].max()
print(f"le salaire maximum est : {salaire_max:.2f}")
salaire_min = data['salaire'].min()
print(f"le salaire minimum est : {salaire_min:.2f}")

le salaire maximum est : 5000.00
le salaire minimum est : 800.00

In [480]:
lis_tuples = data.groupby('poste')['salaire'].count()
print(lis_tuples)

poste
Analyste      2
Commercial    4
Directeur     3
Président     1
Technicien    4
Name: salaire, dtype: int64

In [481]:
moyenne_salaire = data.groupby('poste')['salaire'].mean()
print(f"{moyenne_salaire}")

poste
Analyste      3000.000000
Commercial    1400.000000
Directeur     2758.333333
Président     5000.000000
Technicien    1037.500000
Name: salaire, dtype: float64

In [482]:
print(data['salaire'])
data['salaire'] = data['salaire'].apply(lambda x: x * 1.05)

print(data['salaire'])

0     1100
1     3000
2     1300
3      950
4     3000
5     5000
6     1250
7     1500
8     2450
9     2850
10    2975
11    1250
12    1600
13     800
Name: salaire, dtype: int64
0     1155.00
1     3150.00
2     1365.00
3      997.50
4     3150.00
5     5250.00
6     1312.50
7     1575.00
8     2572.50
9     2992.50
10    3123.75
11    1312.50
12    1680.00
13     840.00
Name: salaire, dtype: float64

In [483]:

data['categorie'] = data['salaire'].apply(lambda x: 'Elevé' if x > 2000 else 'Bas')
print(data[['nom', 'salaire', 'categorie']])

          nom  salaire categorie
0     Calamon  1155.00       Bas
1       Colin  3150.00     Elevé
2       Tozzi  1365.00       Bas
3       James   997.50       Bas
4       Henry  3150.00     Elevé
5      Patton  5250.00     Elevé
6      Ferron  1312.50       Bas
7      Benami  1575.00       Bas
8      Martin  2572.50     Elevé
9       Capon  2992.50     Elevé
10   Dumoulin  3123.75     Elevé
11      Henry  1312.50       Bas
12     Parent  1680.00       Bas
13  Coquillet   840.00       Bas

In [484]:
data[data['categorie'] == 'Elevé']

,nom,num_emp,poste,superieur,date_embauche,salaire,commission,num_dep,categorie
1,Colin,7788,Analyste,7566.0,1987-04-19,3150.00,NaN,20,Elevé
4,Henry,7902,Analyste,7566.0,1981-12-03,3150.00,NaN,20,Elevé
5,Patton,7839,Président,NaN,1981-11-17,5250.00,NaN,10,Elevé
8,Martin,7782,Directeur,7839.0,1981-06-09,2572.50,NaN,10,Elevé
9,Capon,7698,Directeur,7839.0,1981-05-01,2992.50,NaN,30,Elevé
10,Dumoulin,7566,Directeur,7839.0,1981-04-02,3123.75,NaN,20,Elevé

In [485]:
data['poste'].unique()

<StringArray>
['Technicien', 'Analyste', 'Président', 'Commercial', 'Directeur']
Length: 5, dtype: str

In [486]:
data[data['poste'] == 'Technicien'].shape[0]

4

# Partie 5

In [487]:
df_na = data.copy()
df_na.loc[0:2, 'categorie'] = None


df_na.isnull()

,nom,num_emp,poste,superieur,date_embauche,salaire,commission,num_dep,categorie
0,False,False,False,False,False,False,True,False,True
1,False,False,False,False,False,False,True,False,True
2,False,False,False,False,False,False,True,False,True
3,False,False,False,False,False,False,True,False,False
4,False,False,False,False,False,False,True,False,False
5,False,False,False,True,False,False,True,False,False
6,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,True,False,False
9,False,False,False,False,False,False,True,False,False
10,False,False,False,False,False,False,True,False,False
11,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,True,False,False

In [488]:
df_na.isnull().sum()

nom               0
num_emp           0
poste             0
superieur         1
date_embauche     0
salaire           0
commission       10
num_dep           0
categorie         3
dtype: int64

In [489]:
df_na = df_na.dropna(subset=['categorie'])
df_na.isnull().sum()

nom              0
num_emp          0
poste            0
superieur        1
date_embauche    0
salaire          0
commission       7
num_dep          0
categorie        0
dtype: int64

In [490]:
df_na = df_na.dropna()
df_na.isnull().sum()

nom              0
num_emp          0
poste            0
superieur        0
date_embauche    0
salaire          0
commission       0
num_dep          0
categorie        0
dtype: int64

In [491]:
df_na = data.copy()
df_na.isnull().sum()

nom               0
num_emp           0
poste             0
superieur         1
date_embauche     0
salaire           0
commission       10
num_dep           0
categorie         0
dtype: int64

In [492]:
df_na.fillna(0, inplace=True)
df_na.isnull().sum()

nom              0
num_emp          0
poste            0
superieur        0
date_embauche    0
salaire          0
commission       0
num_dep          0
categorie        0
dtype: int64

In [493]:
df_na = data.copy()
df_na = df_na['salaire'].fillna(df_na['salaire'].mean())

# Partie 6

In [494]:
df2 = pd.read_csv('employes.csv')
dataf3 = pd.concat([data, df2], axis=0)
dataf3

,nom,num_emp,poste,superieur,date_embauche,salaire,commission,num_dep,categorie,nom_emp
0,Calamon,7876,Technicien,7788.0,1987-05-23,1155.00,NaN,20,Bas,NaN
1,Colin,7788,Analyste,7566.0,1987-04-19,3150.00,NaN,20,Elevé,NaN
2,Tozzi,7934,Technicien,7782.0,1982-01-23,1365.00,NaN,10,Bas,NaN
3,James,7900,Technicien,7698.0,1981-12-03,997.50,NaN,30,Bas,NaN
4,Henry,7902,Analyste,7566.0,1981-12-03,3150.00,NaN,20,Elevé,NaN
5,Patton,7839,Président,NaN,1981-11-17,5250.00,NaN,10,Elevé,NaN
6,Ferron,7654,Commercial,7698.0,1981-09-28,1312.50,1400.0,30,Bas,NaN
7,Benami,7844,Commercial,7698.0,1981-09-08,1575.00,0.0,30,Bas,NaN
8,Martin,7782,Directeur,7839.0,1981-06-09,2572.50,NaN,10,Elevé,NaN
9,Capon,7698,Directeur,7839.0,1981-05-01,2992.50,NaN,30,Elevé,NaN
10,Dumoulin,7566,Directeur,7839.0,1981-04-02,3123.75,NaN,20,Elevé,NaN
11,Henry,7521,Commercial,7698.0,1981-02-22,1312.50,500.0,30,Bas,NaN
12,Parent,7499,Commercial,7698.0,1981-02-20,1680.00,300.0,30,Bas,NaN
13,Coquillet,7369,Technicien,7902.0,1980-12-17,840.00,NaN,20,Bas,NaN
0,NaN,7369,Technicien,7902.0,1980-12-17,800.00,NaN,20,NaN,Coquillet
1,NaN,7499,Commercial,7698.0,1981-02-20,1600.00,300.0,30,NaN,Parent
2,NaN,7521,Commercial,7698.0,1981-02-22,1250.00,500.0,30,NaN,Henry
3,NaN,7566,Directeur,7839.0,1981-04-02,2975.00,NaN,20,NaN,Dumoulin
4,NaN,7654,Commercial,7698.0,1981-09-28,1250.00,1400.0,30,NaN,Ferron
5,NaN,7698,Directeur,7839.0,1981-05-01,2850.00,NaN,30,NaN,Capon
6,NaN,7782,Directeur,7839.0,1981-06-09,2450.00,NaN,10,NaN,Martin
7,NaN,7788,Analyste,7566.0,1987-04-19,3000.00,NaN,20,NaN,Colin
8,NaN,7839,Président,NaN,1981-11-17,5000.00,NaN,10,NaN,Patton
9,NaN,7844,Commercial,7698.0,1981-09-08,1500.00,0.0,30,NaN,Benami
10,NaN,7876,Technicien,7788.0,1987-05-23,1100.00,NaN,20,NaN,Calamon
11,NaN,7900,Technicien,7698.0,1981-12-03,950.00,NaN,30,NaN,James
12,NaN,7902,Analyste,7566.0,1981-12-03,3000.00,NaN,20,NaN,Henry
13,NaN,7934,Technicien,7782.0,1982-01-23,1300.00,NaN,10,NaN,Tozzi

In [495]:
data2= pd.concat([data, df2], axis=1)
data2

,nom,num_emp,poste,superieur,date_embauche,salaire,commission,num_dep,categorie,num_emp,nom_emp,poste,superieur,date_embauche,salaire,commission,num_dep
0,Calamon,7876,Technicien,7788.0,1987-05-23,1155.00,NaN,20,Bas,7369,Coquillet,Technicien,7902.0,1980-12-17,800,NaN,20
1,Colin,7788,Analyste,7566.0,1987-04-19,3150.00,NaN,20,Elevé,7499,Parent,Commercial,7698.0,1981-02-20,1600,300.0,30
2,Tozzi,7934,Technicien,7782.0,1982-01-23,1365.00,NaN,10,Bas,7521,Henry,Commercial,7698.0,1981-02-22,1250,500.0,30
3,James,7900,Technicien,7698.0,1981-12-03,997.50,NaN,30,Bas,7566,Dumoulin,Directeur,7839.0,1981-04-02,2975,NaN,20
4,Henry,7902,Analyste,7566.0,1981-12-03,3150.00,NaN,20,Elevé,7654,Ferron,Commercial,7698.0,1981-09-28,1250,1400.0,30
5,Patton,7839,Président,NaN,1981-11-17,5250.00,NaN,10,Elevé,7698,Capon,Directeur,7839.0,1981-05-01,2850,NaN,30
6,Ferron,7654,Commercial,7698.0,1981-09-28,1312.50,1400.0,30,Bas,7782,Martin,Directeur,7839.0,1981-06-09,2450,NaN,10
7,Benami,7844,Commercial,7698.0,1981-09-08,1575.00,0.0,30,Bas,7788,Colin,Analyste,7566.0,1987-04-19,3000,NaN,20
8,Martin,7782,Directeur,7839.0,1981-06-09,2572.50,NaN,10,Elevé,7839,Patton,Président,NaN,1981-11-17,5000,NaN,10
9,Capon,7698,Directeur,7839.0,1981-05-01,2992.50,NaN,30,Elevé,7844,Benami,Commercial,7698.0,1981-09-08,1500,0.0,30
10,Dumoulin,7566,Directeur,7839.0,1981-04-02,3123.75,NaN,20,Elevé,7876,Calamon,Technicien,7788.0,1987-05-23,1100,NaN,20
11,Henry,7521,Commercial,7698.0,1981-02-22,1312.50,500.0,30,Bas,7900,James,Technicien,7698.0,1981-12-03,950,NaN,30
12,Parent,7499,Commercial,7698.0,1981-02-20,1680.00,300.0,30,Bas,7902,Henry,Analyste,7566.0,1981-12-03,3000,NaN,20
13,Coquillet,7369,Technicien,7902.0,1980-12-17,840.00,NaN,20,Bas,7934,Tozzi,Technicien,7782.0,1982-01-23,1300,NaN,10

In [496]:
merged_df=pd.merge(data, df2, on='num_emp')
merged_df

,nom,num_emp,poste_x,superieur_x,date_embauche_x,salaire_x,commission_x,num_dep_x,categorie,nom_emp,poste_y,superieur_y,date_embauche_y,salaire_y,commission_y,num_dep_y
0,Calamon,7876,Technicien,7788.0,1987-05-23,1155.00,NaN,20,Bas,Calamon,Technicien,7788.0,1987-05-23,1100,NaN,20
1,Colin,7788,Analyste,7566.0,1987-04-19,3150.00,NaN,20,Elevé,Colin,Analyste,7566.0,1987-04-19,3000,NaN,20
2,Tozzi,7934,Technicien,7782.0,1982-01-23,1365.00,NaN,10,Bas,Tozzi,Technicien,7782.0,1982-01-23,1300,NaN,10
3,James,7900,Technicien,7698.0,1981-12-03,997.50,NaN,30,Bas,James,Technicien,7698.0,1981-12-03,950,NaN,30
4,Henry,7902,Analyste,7566.0,1981-12-03,3150.00,NaN,20,Elevé,Henry,Analyste,7566.0,1981-12-03,3000,NaN,20
5,Patton,7839,Président,NaN,1981-11-17,5250.00,NaN,10,Elevé,Patton,Président,NaN,1981-11-17,5000,NaN,10
6,Ferron,7654,Commercial,7698.0,1981-09-28,1312.50,1400.0,30,Bas,Ferron,Commercial,7698.0,1981-09-28,1250,1400.0,30
7,Benami,7844,Commercial,7698.0,1981-09-08,1575.00,0.0,30,Bas,Benami,Commercial,7698.0,1981-09-08,1500,0.0,30
8,Martin,7782,Directeur,7839.0,1981-06-09,2572.50,NaN,10,Elevé,Martin,Directeur,7839.0,1981-06-09,2450,NaN,10
9,Capon,7698,Directeur,7839.0,1981-05-01,2992.50,NaN,30,Elevé,Capon,Directeur,7839.0,1981-05-01,2850,NaN,30
10,Dumoulin,7566,Directeur,7839.0,1981-04-02,3123.75,NaN,20,Elevé,Dumoulin,Directeur,7839.0,1981-04-02,2975,NaN,20
11,Henry,7521,Commercial,7698.0,1981-02-22,1312.50,500.0,30,Bas,Henry,Commercial,7698.0,1981-02-22,1250,500.0,30
12,Parent,7499,Commercial,7698.0,1981-02-20,1680.00,300.0,30,Bas,Parent,Commercial,7698.0,1981-02-20,1600,300.0,30
13,Coquillet,7369,Technicien,7902.0,1980-12-17,840.00,NaN,20,Bas,Coquillet,Technicien,7902.0,1980-12-17,800,NaN,20

In [497]:
merged_df=pd.merge(data, df2, on='num_emp', how='left')
merged_df

,nom,num_emp,poste_x,superieur_x,date_embauche_x,salaire_x,commission_x,num_dep_x,categorie,nom_emp,poste_y,superieur_y,date_embauche_y,salaire_y,commission_y,num_dep_y
0,Calamon,7876,Technicien,7788.0,1987-05-23,1155.00,NaN,20,Bas,Calamon,Technicien,7788.0,1987-05-23,1100,NaN,20
1,Colin,7788,Analyste,7566.0,1987-04-19,3150.00,NaN,20,Elevé,Colin,Analyste,7566.0,1987-04-19,3000,NaN,20
2,Tozzi,7934,Technicien,7782.0,1982-01-23,1365.00,NaN,10,Bas,Tozzi,Technicien,7782.0,1982-01-23,1300,NaN,10
3,James,7900,Technicien,7698.0,1981-12-03,997.50,NaN,30,Bas,James,Technicien,7698.0,1981-12-03,950,NaN,30
4,Henry,7902,Analyste,7566.0,1981-12-03,3150.00,NaN,20,Elevé,Henry,Analyste,7566.0,1981-12-03,3000,NaN,20
5,Patton,7839,Président,NaN,1981-11-17,5250.00,NaN,10,Elevé,Patton,Président,NaN,1981-11-17,5000,NaN,10
6,Ferron,7654,Commercial,7698.0,1981-09-28,1312.50,1400.0,30,Bas,Ferron,Commercial,7698.0,1981-09-28,1250,1400.0,30
7,Benami,7844,Commercial,7698.0,1981-09-08,1575.00,0.0,30,Bas,Benami,Commercial,7698.0,1981-09-08,1500,0.0,30
8,Martin,7782,Directeur,7839.0,1981-06-09,2572.50,NaN,10,Elevé,Martin,Directeur,7839.0,1981-06-09,2450,NaN,10
9,Capon,7698,Directeur,7839.0,1981-05-01,2992.50,NaN,30,Elevé,Capon,Directeur,7839.0,1981-05-01,2850,NaN,30
10,Dumoulin,7566,Directeur,7839.0,1981-04-02,3123.75,NaN,20,Elevé,Dumoulin,Directeur,7839.0,1981-04-02,2975,NaN,20
11,Henry,7521,Commercial,7698.0,1981-02-22,1312.50,500.0,30,Bas,Henry,Commercial,7698.0,1981-02-22,1250,500.0,30
12,Parent,7499,Commercial,7698.0,1981-02-20,1680.00,300.0,30,Bas,Parent,Commercial,7698.0,1981-02-20,1600,300.0,30
13,Coquillet,7369,Technicien,7902.0,1980-12-17,840.00,NaN,20,Bas,Coquillet,Technicien,7902.0,1980-12-17,800,NaN,20

In [498]:
df2.rename(columns={'nom_emp': 'nom'}, inplace=True)

In [499]:


concat_df = pd.concat([data, df2], axis=0)
fus_df =pd.concat([data, df2], axis=1)
fus_df = pd.merge(data, df2, on='num_emp')
fus_df = pd.merge(data, df2, on='num_emp', how='left')
fus_df

,nom_x,num_emp,poste_x,superieur_x,date_embauche_x,salaire_x,commission_x,num_dep_x,categorie,nom_y,poste_y,superieur_y,date_embauche_y,salaire_y,commission_y,num_dep_y
0,Calamon,7876,Technicien,7788.0,1987-05-23,1155.00,NaN,20,Bas,Calamon,Technicien,7788.0,1987-05-23,1100,NaN,20
1,Colin,7788,Analyste,7566.0,1987-04-19,3150.00,NaN,20,Elevé,Colin,Analyste,7566.0,1987-04-19,3000,NaN,20
2,Tozzi,7934,Technicien,7782.0,1982-01-23,1365.00,NaN,10,Bas,Tozzi,Technicien,7782.0,1982-01-23,1300,NaN,10
3,James,7900,Technicien,7698.0,1981-12-03,997.50,NaN,30,Bas,James,Technicien,7698.0,1981-12-03,950,NaN,30
4,Henry,7902,Analyste,7566.0,1981-12-03,3150.00,NaN,20,Elevé,Henry,Analyste,7566.0,1981-12-03,3000,NaN,20
5,Patton,7839,Président,NaN,1981-11-17,5250.00,NaN,10,Elevé,Patton,Président,NaN,1981-11-17,5000,NaN,10
6,Ferron,7654,Commercial,7698.0,1981-09-28,1312.50,1400.0,30,Bas,Ferron,Commercial,7698.0,1981-09-28,1250,1400.0,30
7,Benami,7844,Commercial,7698.0,1981-09-08,1575.00,0.0,30,Bas,Benami,Commercial,7698.0,1981-09-08,1500,0.0,30
8,Martin,7782,Directeur,7839.0,1981-06-09,2572.50,NaN,10,Elevé,Martin,Directeur,7839.0,1981-06-09,2450,NaN,10
9,Capon,7698,Directeur,7839.0,1981-05-01,2992.50,NaN,30,Elevé,Capon,Directeur,7839.0,1981-05-01,2850,NaN,30
10,Dumoulin,7566,Directeur,7839.0,1981-04-02,3123.75,NaN,20,Elevé,Dumoulin,Directeur,7839.0,1981-04-02,2975,NaN,20
11,Henry,7521,Commercial,7698.0,1981-02-22,1312.50,500.0,30,Bas,Henry,Commercial,7698.0,1981-02-22,1250,500.0,30
12,Parent,7499,Commercial,7698.0,1981-02-20,1680.00,300.0,30,Bas,Parent,Commercial,7698.0,1981-02-20,1600,300.0,30
13,Coquillet,7369,Technicien,7902.0,1980-12-17,840.00,NaN,20,Bas,Coquillet,Technicien,7902.0,1980-12-17,800,NaN,20

# Partie 7

In [500]:
data["date_embauche"] = data["date_embauche"].astype('datetime64[ns]')
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   nom            14 non-null     str
 1   num_emp        14 non-null     int64
 2   poste          14 non-null     str
 3   superieur      13 non-null     float64
 4   date_embauche  14 non-null     datetime64[ns]
 5   salaire        14 non-null     float64
 6   commission     4 non-null      object
 7   num_dep        14 non-null     int64
 8   categorie      14 non-null     str
dtypes: datetime64[ns](1), float64(2), int64(2), object(1), str(3)
memory usage: 1.1+ KB