In [1078]:
import pandas as pd

In [1079]:
L1 = [[1, 2, 3, 4, 5],
      [6, 7, 8, 9, 10]]
df = pd.DataFrame(L1, index=['line1', 'line2'], columns=['col1','col2','col3','col4','col5'], dtype=float, copy=True)
df

       col1  col2  col3  col4  col5
line1   1.0   2.0   3.0   4.0   5.0
line2   6.0   7.0   8.0   9.0  10.0

In [1080]:
dictionaire = {'names': ['ali', 'ahmed'], 'age': [20, 70]}
df2 = pd.DataFrame(dictionaire, index=['line1', 'line2'])
df2

       names  age
line1    ali   20
line2  ahmed   70

In [1081]:
serie1 = pd.Series(L1, index=None, name="serie1", dtype=None, copy=False/True)
serie1

0     [1, 2, 3, 4, 5]
1    [6, 7, 8, 9, 10]
Name: serie1, dtype: object

In [1082]:
dataframe2 = pd.read_csv('./employes.csv', sep=',', header=0)
dataframe2.head(3)

,num_emp,nom_emp,poste,superieur,date_embauche,salaire,commission,num_dep
0,7369,Coquillet,Technicien,7902,1980-12-17,800,NaN,20.0
1,7499,Parent,Commercial,76981981-02-20,1600,300,30.0,NaN
2,7521,Henry,Commercial,7698,1981-02-22,1250,500.0,30.0

In [1083]:
dataframe2.tail(3)

,num_emp,nom_emp,poste,superieur,date_embauche,salaire,commission,num_dep
11,7900,James,Technicien,7698,1981-12-03,950,NaN,30.0
12,7902,Henry,Analyste,7566,1981-12-03,3000,NaN,20.0
13,7934,Tozzi,Technicien,7782,1982-01-23,1300,NaN,10.0

In [1084]:
dataframe2.shape

(14, 8)

In [1085]:
dataframe2.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   num_emp        14 non-null     int64
 1   nom_emp        14 non-null     str
 2   poste          14 non-null     str
 3   superieur      13 non-null     str
 4   date_embauche  14 non-null     str
 5   salaire        14 non-null     int64
 6   commission     4 non-null      float64
 7   num_dep        13 non-null     float64
dtypes: float64(2), int64(2), str(4)
memory usage: 1.0 KB

In [1086]:
dataframe2.describe()

           num_emp      salaire   commission    num_dep
count    14.000000    14.000000     4.000000  13.000000
mean   7726.571429  1980.357143   482.500000  21.538462
std     178.294361  1270.303514   653.114334   8.006408
min    7369.000000   300.000000     0.000000  10.000000
25%    7588.000000  1137.500000    22.500000  20.000000
50%    7785.000000  1400.000000   265.000000  20.000000
75%    7868.000000  2943.750000   725.000000  30.000000
max    7934.000000  5000.000000  1400.000000  30.000000

In [1087]:
dataframe2.columns

Index(['num_emp', 'nom_emp', 'poste', 'superieur', 'date_embauche', 'salaire',
       'commission', 'num_dep'],
      dtype='str')

In [1088]:
dataframe2

,num_emp,nom_emp,poste,superieur,date_embauche,salaire,commission,num_dep
0,7369,Coquillet,Technicien,7902,1980-12-17,800,NaN,20.0
1,7499,Parent,Commercial,76981981-02-20,1600,300,30.0,NaN
2,7521,Henry,Commercial,7698,1981-02-22,1250,500.0,30.0
3,7566,Dumoulin,Directeur,7839,1981-04-02,2975,NaN,20.0
4,7654,Ferron,Commercial,7698,1981-09-28,1250,1400.0,30.0
5,7698,Capon,Directeur,7839,1981-05-01,2850,NaN,30.0
6,7782,Martin,Directeur,7839,1981-06-09,2450,NaN,10.0
7,7788,Colin,Analyste,7566,1987-04-19,3000,NaN,20.0
8,7839,Patton,Président,NaN,1981-11-17,5000,NaN,10.0
9,7844,Benami,Commercial,7698,1981-09-08,1500,0.0,30.0
10,7876,Calamon,Technicien,7788,1987-05-23,1100,NaN,20.0
11,7900,James,Technicien,7698,1981-12-03,950,NaN,30.0
12,7902,Henry,Analyste,7566,1981-12-03,3000,NaN,20.0
13,7934,Tozzi,Technicien,7782,1982-01-23,1300,NaN,10.0

In [1089]:
noms_emp = dataframe2['nom_emp']
noms_emp

0     Coquillet
1        Parent
2         Henry
3      Dumoulin
4        Ferron
5         Capon
6        Martin
7         Colin
8        Patton
9        Benami
10      Calamon
11        James
12        Henry
13        Tozzi
Name: nom_emp, dtype: str

In [1090]:
dataframe2[['nom_emp', 'poste']]

      nom_emp       poste
0   Coquillet  Technicien
1      Parent  Commercial
2       Henry  Commercial
3    Dumoulin   Directeur
4      Ferron  Commercial
5       Capon   Directeur
6      Martin   Directeur
7       Colin    Analyste
8      Patton   Président
9      Benami  Commercial
10    Calamon  Technicien
11      James  Technicien
12      Henry    Analyste
13      Tozzi  Technicien

In [1091]:
dataframe2.loc[0]

num_emp                7369
nom_emp           Coquillet
poste            Technicien
superieur              7902
date_embauche    1980-12-17
salaire                 800
commission              NaN
num_dep                20.0
Name: 0, dtype: object

In [1092]:
dataframe2.loc[0,"poste"]
df2.loc['line1', 'names']# it accept only name of row and name of columns not indexes

'ali'

In [1093]:
# dataframe2.loc[0,2] # error it accept only column names and row labels

In [1094]:
df2.iloc[0, 1] # it use only indexes

np.int64(20)

In [1095]:
dataframe2

,num_emp,nom_emp,poste,superieur,date_embauche,salaire,commission,num_dep
0,7369,Coquillet,Technicien,7902,1980-12-17,800,NaN,20.0
1,7499,Parent,Commercial,76981981-02-20,1600,300,30.0,NaN
2,7521,Henry,Commercial,7698,1981-02-22,1250,500.0,30.0
3,7566,Dumoulin,Directeur,7839,1981-04-02,2975,NaN,20.0
4,7654,Ferron,Commercial,7698,1981-09-28,1250,1400.0,30.0
5,7698,Capon,Directeur,7839,1981-05-01,2850,NaN,30.0
6,7782,Martin,Directeur,7839,1981-06-09,2450,NaN,10.0
7,7788,Colin,Analyste,7566,1987-04-19,3000,NaN,20.0
8,7839,Patton,Président,NaN,1981-11-17,5000,NaN,10.0
9,7844,Benami,Commercial,7698,1981-09-08,1500,0.0,30.0
10,7876,Calamon,Technicien,7788,1987-05-23,1100,NaN,20.0
11,7900,James,Technicien,7698,1981-12-03,950,NaN,30.0
12,7902,Henry,Analyste,7566,1981-12-03,3000,NaN,20.0
13,7934,Tozzi,Technicien,7782,1982-01-23,1300,NaN,10.0

In [1096]:
dataframe2.at[0, "num_emp"]

np.int64(7369)

In [1097]:
dataframe2.iat[0, 0]

np.int64(7369)

# Filtrage

In [1098]:
dataframe2[(dataframe2['salaire'] > 1250) & (dataframe2['poste'] == 'Technicien') ]

,num_emp,nom_emp,poste,superieur,date_embauche,salaire,commission,num_dep
13,7934,Tozzi,Technicien,7782,1982-01-23,1300,NaN,10.0

In [1099]:
dataframe2[dataframe2['poste'].isin(["Commercial", "Technicien"])]

,num_emp,nom_emp,poste,superieur,date_embauche,salaire,commission,num_dep
0,7369,Coquillet,Technicien,7902,1980-12-17,800,NaN,20.0
1,7499,Parent,Commercial,76981981-02-20,1600,300,30.0,NaN
2,7521,Henry,Commercial,7698,1981-02-22,1250,500.0,30.0
4,7654,Ferron,Commercial,7698,1981-09-28,1250,1400.0,30.0
9,7844,Benami,Commercial,7698,1981-09-08,1500,0.0,30.0
10,7876,Calamon,Technicien,7788,1987-05-23,1100,NaN,20.0
11,7900,James,Technicien,7698,1981-12-03,950,NaN,30.0
13,7934,Tozzi,Technicien,7782,1982-01-23,1300,NaN,10.0

In [1100]:
dataframe2.isna().sum()

num_emp           0
nom_emp           0
poste             0
superieur         1
date_embauche     0
salaire           0
commission       10
num_dep           1
dtype: int64

In [1101]:
dataframe2.dropna()

,num_emp,nom_emp,poste,superieur,date_embauche,salaire,commission,num_dep
2,7521,Henry,Commercial,7698,1981-02-22,1250,500.0,30.0
4,7654,Ferron,Commercial,7698,1981-09-28,1250,1400.0,30.0
9,7844,Benami,Commercial,7698,1981-09-08,1500,0.0,30.0

In [1102]:
dataframe2 = dataframe2.replace("Technicien", "tech")
dataframe2

,num_emp,nom_emp,poste,superieur,date_embauche,salaire,commission,num_dep
0,7369,Coquillet,tech,7902,1980-12-17,800,NaN,20.0
1,7499,Parent,Commercial,76981981-02-20,1600,300,30.0,NaN
2,7521,Henry,Commercial,7698,1981-02-22,1250,500.0,30.0
3,7566,Dumoulin,Directeur,7839,1981-04-02,2975,NaN,20.0
4,7654,Ferron,Commercial,7698,1981-09-28,1250,1400.0,30.0
5,7698,Capon,Directeur,7839,1981-05-01,2850,NaN,30.0
6,7782,Martin,Directeur,7839,1981-06-09,2450,NaN,10.0
7,7788,Colin,Analyste,7566,1987-04-19,3000,NaN,20.0
8,7839,Patton,Président,NaN,1981-11-17,5000,NaN,10.0
9,7844,Benami,Commercial,7698,1981-09-08,1500,0.0,30.0
10,7876,Calamon,tech,7788,1987-05-23,1100,NaN,20.0
11,7900,James,tech,7698,1981-12-03,950,NaN,30.0
12,7902,Henry,Analyste,7566,1981-12-03,3000,NaN,20.0
13,7934,Tozzi,tech,7782,1982-01-23,1300,NaN,10.0

In [1103]:
dataframe2.isna()

,num_emp,nom_emp,poste,superieur,date_embauche,salaire,commission,num_dep
0,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,True,False
6,False,False,False,False,False,False,True,False
7,False,False,False,False,False,False,True,False
8,False,False,False,True,False,False,True,False
9,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,True,False
11,False,False,False,False,False,False,True,False
12,False,False,False,False,False,False,True,False
13,False,False,False,False,False,False,True,False

In [1104]:
#dataframe2 = dataframe2["poste"].fillna("technicien")
#dataframe2 = dataframe2["salaire"].fillna(3000)

In [1105]:
L1 = [[1, 2, 3, 4, 5],
      [6, 7, None, 0, None]]
df3 = pd.DataFrame(L1, index=['line1', 'line2'], columns=['col1','col2','col3','col4','col5'], dtype=float, copy=True)
df3

       col1  col2  col3  col4  col5
line1   1.0   2.0   3.0   4.0   5.0
line2   6.0   7.0   NaN   0.0   NaN

In [1106]:

df3 = df3.interpolate(method='linear')
df3

       col1  col2  col3  col4  col5
line1   1.0   2.0   3.0   4.0   5.0
line2   6.0   7.0   3.0   0.0   5.0

In [1107]:
dataframe2

,num_emp,nom_emp,poste,superieur,date_embauche,salaire,commission,num_dep
0,7369,Coquillet,tech,7902,1980-12-17,800,NaN,20.0
1,7499,Parent,Commercial,76981981-02-20,1600,300,30.0,NaN
2,7521,Henry,Commercial,7698,1981-02-22,1250,500.0,30.0
3,7566,Dumoulin,Directeur,7839,1981-04-02,2975,NaN,20.0
4,7654,Ferron,Commercial,7698,1981-09-28,1250,1400.0,30.0
5,7698,Capon,Directeur,7839,1981-05-01,2850,NaN,30.0
6,7782,Martin,Directeur,7839,1981-06-09,2450,NaN,10.0
7,7788,Colin,Analyste,7566,1987-04-19,3000,NaN,20.0
8,7839,Patton,Président,NaN,1981-11-17,5000,NaN,10.0
9,7844,Benami,Commercial,7698,1981-09-08,1500,0.0,30.0
10,7876,Calamon,tech,7788,1987-05-23,1100,NaN,20.0
11,7900,James,tech,7698,1981-12-03,950,NaN,30.0
12,7902,Henry,Analyste,7566,1981-12-03,3000,NaN,20.0
13,7934,Tozzi,tech,7782,1982-01-23,1300,NaN,10.0

In [1108]:
dataframe2["bonus"] = dataframe2["salaire"] * 0.1
dataframe2

,num_emp,nom_emp,poste,superieur,date_embauche,salaire,commission,num_dep,bonus
0,7369,Coquillet,tech,7902,1980-12-17,800,NaN,20.0,80.0
1,7499,Parent,Commercial,76981981-02-20,1600,300,30.0,NaN,30.0
2,7521,Henry,Commercial,7698,1981-02-22,1250,500.0,30.0,125.0
3,7566,Dumoulin,Directeur,7839,1981-04-02,2975,NaN,20.0,297.5
4,7654,Ferron,Commercial,7698,1981-09-28,1250,1400.0,30.0,125.0
5,7698,Capon,Directeur,7839,1981-05-01,2850,NaN,30.0,285.0
6,7782,Martin,Directeur,7839,1981-06-09,2450,NaN,10.0,245.0
7,7788,Colin,Analyste,7566,1987-04-19,3000,NaN,20.0,300.0
8,7839,Patton,Président,NaN,1981-11-17,5000,NaN,10.0,500.0
9,7844,Benami,Commercial,7698,1981-09-08,1500,0.0,30.0,150.0
10,7876,Calamon,tech,7788,1987-05-23,1100,NaN,20.0,110.0
11,7900,James,tech,7698,1981-12-03,950,NaN,30.0,95.0
12,7902,Henry,Analyste,7566,1981-12-03,3000,NaN,20.0,300.0
13,7934,Tozzi,tech,7782,1982-01-23,1300,NaN,10.0,130.0

In [1109]:
dataframe2 = dataframe2.drop("bonus", axis=1) # axis=1 for columns and axis=0 for rows
dataframe2

,num_emp,nom_emp,poste,superieur,date_embauche,salaire,commission,num_dep
0,7369,Coquillet,tech,7902,1980-12-17,800,NaN,20.0
1,7499,Parent,Commercial,76981981-02-20,1600,300,30.0,NaN
2,7521,Henry,Commercial,7698,1981-02-22,1250,500.0,30.0
3,7566,Dumoulin,Directeur,7839,1981-04-02,2975,NaN,20.0
4,7654,Ferron,Commercial,7698,1981-09-28,1250,1400.0,30.0
5,7698,Capon,Directeur,7839,1981-05-01,2850,NaN,30.0
6,7782,Martin,Directeur,7839,1981-06-09,2450,NaN,10.0
7,7788,Colin,Analyste,7566,1987-04-19,3000,NaN,20.0
8,7839,Patton,Président,NaN,1981-11-17,5000,NaN,10.0
9,7844,Benami,Commercial,7698,1981-09-08,1500,0.0,30.0
10,7876,Calamon,tech,7788,1987-05-23,1100,NaN,20.0
11,7900,James,tech,7698,1981-12-03,950,NaN,30.0
12,7902,Henry,Analyste,7566,1981-12-03,3000,NaN,20.0
13,7934,Tozzi,tech,7782,1982-01-23,1300,NaN,10.0

In [1110]:
dataframe2 = dataframe2.rename(columns={"salaire": "salaire_net"})
dataframe2

,num_emp,nom_emp,poste,superieur,date_embauche,salaire_net,commission,num_dep
0,7369,Coquillet,tech,7902,1980-12-17,800,NaN,20.0
1,7499,Parent,Commercial,76981981-02-20,1600,300,30.0,NaN
2,7521,Henry,Commercial,7698,1981-02-22,1250,500.0,30.0
3,7566,Dumoulin,Directeur,7839,1981-04-02,2975,NaN,20.0
4,7654,Ferron,Commercial,7698,1981-09-28,1250,1400.0,30.0
5,7698,Capon,Directeur,7839,1981-05-01,2850,NaN,30.0
6,7782,Martin,Directeur,7839,1981-06-09,2450,NaN,10.0
7,7788,Colin,Analyste,7566,1987-04-19,3000,NaN,20.0
8,7839,Patton,Président,NaN,1981-11-17,5000,NaN,10.0
9,7844,Benami,Commercial,7698,1981-09-08,1500,0.0,30.0
10,7876,Calamon,tech,7788,1987-05-23,1100,NaN,20.0
11,7900,James,tech,7698,1981-12-03,950,NaN,30.0
12,7902,Henry,Analyste,7566,1981-12-03,3000,NaN,20.0
13,7934,Tozzi,tech,7782,1982-01-23,1300,NaN,10.0

In [1111]:
dataframe2.insert(loc=3, column="test", value=0) # create a new column with name num_emp and fill it with 0
dataframe2

,num_emp,nom_emp,poste,test,superieur,date_embauche,salaire_net,commission,num_dep
0,7369,Coquillet,tech,0,7902,1980-12-17,800,NaN,20.0
1,7499,Parent,Commercial,0,76981981-02-20,1600,300,30.0,NaN
2,7521,Henry,Commercial,0,7698,1981-02-22,1250,500.0,30.0
3,7566,Dumoulin,Directeur,0,7839,1981-04-02,2975,NaN,20.0
4,7654,Ferron,Commercial,0,7698,1981-09-28,1250,1400.0,30.0
5,7698,Capon,Directeur,0,7839,1981-05-01,2850,NaN,30.0
6,7782,Martin,Directeur,0,7839,1981-06-09,2450,NaN,10.0
7,7788,Colin,Analyste,0,7566,1987-04-19,3000,NaN,20.0
8,7839,Patton,Président,0,NaN,1981-11-17,5000,NaN,10.0
9,7844,Benami,Commercial,0,7698,1981-09-08,1500,0.0,30.0
10,7876,Calamon,tech,0,7788,1987-05-23,1100,NaN,20.0
11,7900,James,tech,0,7698,1981-12-03,950,NaN,30.0
12,7902,Henry,Analyste,0,7566,1981-12-03,3000,NaN,20.0
13,7934,Tozzi,tech,0,7782,1982-01-23,1300,NaN,10.0

In [1112]:
def add_bonus(row):
    return row.fillna(None)
dataframe2 = dataframe2.apply(add_bonus, axis=1)

In [1113]:
def add_bonus(row):
    return row.fillna(None)
dataframe2 = dataframe2.apply(add_bonus, axis=1)

In [1114]:
dataframe2.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
dtype: bool

In [1115]:
dataframe2.head()

,num_emp,nom_emp,poste,test,superieur,date_embauche,salaire_net,commission,num_dep
0,7369,Coquillet,tech,0,7902,1980-12-17,800,NaN,20.0
1,7499,Parent,Commercial,0,76981981-02-20,1600,300,30.0,NaN
2,7521,Henry,Commercial,0,7698,1981-02-22,1250,500.0,30.0
3,7566,Dumoulin,Directeur,0,7839,1981-04-02,2975,NaN,20.0
4,7654,Ferron,Commercial,0,7698,1981-09-28,1250,1400.0,30.0

In [1116]:
dataframe2 = dataframe2.drop_duplicates()

# Groupement , Agrégation et Tri

In [1117]:
dataframe2.groupby("poste").agg({"salaire_net": "mean", "commission" : "sum"})

            salaire_net  commission
poste
Analyste           3000         0.0
Commercial         1500      1930.0
Directeur          2975         0.0
Président          5000         0.0
tech               1300         0.0

In [1125]:
dataframe2.pivot_table(
    index="commission",
    columns="salaire_net",
    values="poste",
    aggfunc="count",
    fill_value=0
)

salaire_net  300   1250  1500
commission
0.0             0     0     1
30.0            1     0     0
500.0           0     1     0
1400.0          0     1     0